#!/bin/bash

echo "Uso: hos {comando}"
echo ""
echo "Comandos disponibles:"
# New_Commands:
echo "  home            Redirecciona al directorio donde se encuentran los proyectos de HOStudios"
echo " "
echo "  code            Este comando abre el proyecto especificado con vs code."
echo "                  Al no indicar un proyecto se muestra la lista de estos (listar: hos code)"
echo " "
echo "  rcode           Este comando abre el proyecto especificado con vs code, pero en el contenedor de desarrrollo"
echo "                  Al no indicar un proyecto se muestra la lista de estos (listar: hos rcode)"
echo " "
echo "  compose         Este comando utiliza los docker compose de los proyectos, desde cualquier ubicacion."
echo "                  Pude usar cualquier comando compose a posterior del proyecto (ejemplo: hos compose etherealb up -d)"
echo "                  Al no indicar un proyecto se muestra la lista de estos (listar: hos compose)"
echo " "
echo "  attach          Este comando ingresa al contenedor de desarrollo, para utilizarlo desde cualquier lugar que estes"  
echo "                  Al no indicar un proyecto se muestra la lista de estos (listar: hos attach)"
echo " "  