alias ll='lsd -lh --group-dirs=first'
alias la='lsd -a --group-dirs=first'
alias l='lsd --group-dirs=first'
alias lla='lsd -lha --group-dirs=first'
alias ls='lsd --group-dirs=first'
alias cat='bat'
alias kitty='kitty --single-instance'
alias cdgithub='cd /home/$USER/Documentos/Repos/My-Github/'
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
alias config='/usr/bin/git --git-dir=/home/oscar/.cfg/ --work-tree=/home/oscar'
alias config='/usr/bin/git --git-dir=/home/oscar/.cfg/ --work-tree=/home/oscar'
alias bitwardenup='~/.config/update-bitwarden.sh'
alias discordup='~/.config/update-discord.sh'